### ISSUE TITLE
in guest_func_73448: VerifierError { location: inst417, message: "inconsistent with global location %rax (regmove.i32 v110, %9 -> %0)" }

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/lucet#361] opened 2019-11-11 10:03 UTC
To reproduce, run lucetc 0.4.1 on [this file](https://cloud.whitequark.org/s/4x8wESDAZETfxd7).

**Comment by awortman-fastly** [comment] 2019-11-11 20:23
Through a complete fluke I tried reproducing on an old lucet and failed -- `yosys-lucetc-issue.wasm` built just fine. If you're building lucet from source, `0b7598bf3fa24fbea5d7012331d9115cc3e5f55a` should be usable here.

It looks like this is related to cranelift building with basic blocks rather than EBBs. In the next commit, `6f29071eea2b00b50300b280ba0424521808199d`, cranelift is bumped to 0.43.1, picking up a change that made basic blocks default, and yields the same verifier error.

I noted the working/broken clif in https://github.com/fastly/lucet/commit/5f383d5f77a1520fb40a4d80d262c777db293d0d for the moment. I'll also minimize and report an issue (+ fix if it's straightforward) to cranelift.

**Comment by awortman-fastly** [comment] 2019-11-27 01:36
:heavy_check_mark: `master` now uses cranelift 0.51.0, and lucetc happily builds `yosys-lucetc-issue.wasm`.
:x: something somewhere goes wrong?
![yosys banner but then a crash](https://user-images.githubusercontent.com/49215183/69685557-ab545100-1071-11ea-862a-e6314db0d9d4.png)

generally `help` seems to work, but entering a command incorrectly does the above (not knowing yosys I don't know if that's approximately right or not?)

the faulting function is
```
19cb4ea func[79221]:
 19cb4eb: 00                         | unreachable
 19cb4ec: 00                         | unreachable
 19cb4ed: 0b                         | end
```
so that doesn't seem like a lucetc error.

also of note: the compiled binary fails at runtime with a `HeapOverflow` unless `lucetc` is run with a larger-than-default `--min-reserved-size`. I set `--min-reserved-size 4GiB` and things seem to work, so that's likely just our aggressive default memory settings.

**Comment by whitequark** [comment] 2019-11-27 11:20
>  `master` now uses cranelift 0.51.0, and lucetc happily builds `yosys-lucetc-issue.wasm`.

Thank you!

> also of note: the compiled binary fails at runtime with a `HeapOverflow` unless `lucetc` is run with a larger-than-default `--min-reserved-size`. I set `--min-reserved-size 4GiB` and things seem to work, so that's likely just our aggressive default memory settings.

Yes, this is not unexpected.

>  something somewhere goes wrong?

> generally `help` seems to work, but entering a command incorrectly does the above (not knowing yosys I don't know if that's approximately right or not?)

So the story goes, Yosys *sort of* works (I can even synthesize very simple designs), but seemingly at random, some commands in some circumstances lead to memory corruption and/or violate libc++ invariants. Yosys is pretty well-tested so it seems unlikely (but possible) that this is an ubiquitous memory corruption bug in Yosys itself. It seems more likely that some combination of Yosys and the WASM environment is the culprit.

Unfortunately, there appears to be no practical way to figure out *what* goes wrong. Wasmtime, technically speaking, does emit debug information, but... by my estimates, it takes somewhere on the order of *hours per invocation* (it's not cached, and my patience runs out after around 15 minutes), bytecodealliance/wasmtime#537. Lucetc does not even try to emit debug information, #364.

Although I do have experience debugging applications with zero debug information and mysterious memory corruption, those applications generally are small embedded firmware that I wrote ~entirely from scratch and know inside out. It is not a method that works on a large existing C++ codebase I am merely familiar with. I could probably still get it done by spending several weeks of my time on systematically reducing a crash, but I can't afford that.

**Comment by iximeow** [comment] 2020-01-24 20:11
Closing as the upstream bug is now also closed. Debug information is WIP, but tracked in #364.

**Closed by iximeow** 2020-01-24 20:11 UTC
