### ISSUE TITLE
cargo cannot resolve dependency

### ISSUE THREAD

**Issue by EmotionalSnow** [bytecodealliance/lucet#597] opened 2020-10-28 22:26 UTC
Unfortunately `cargo install lucetc` fails immediately:

```
Updating crates.io index
Installing lucetc v0.6.1
error: failed to compile `lucetc v0.6.1`, intermediate artifacts can be found at `/tmp/cargo-installg4Nr8d`

Caused by:
  failed to select a version for the requirement `wabt = "^0.9.2"`
  candidate versions found which didn't match: 0.10.0, 0.9.1, 0.9.0, ...
  location searched: crates.io index
  required by package `lucetc v0.6.1`
```

**Comment by jedisct1** [comment] 2020-10-28 23:10
If you recently updated the main repository, you should update the submodules as well:

```sh
git submodule update --init
```

**Comment by jedisct1** [comment] 2020-10-28 23:16
Scratch that. If you used `cargo install`, the issue is rather that we forgot to update some packages on `crates.io`, oops!

Thanks for reporting this. It will be fixed as soon as possible.

Meanwhile the easiest way to install `Lucet` is to clone this repository and use `make install`.

**Comment by jedisct1** [comment] 2020-10-28 23:24
Update: `wabt` 0.9.2, that `lucetc` depends on, was [yanked](https://crates.io/crates/wabt) by its author.

In the current development version of `lucet`, that dependency was changed back to version `0.9.1`. So, compiling directly from this directory should work as expected.

**Closed** 2020-10-29 12:35 UTC
